Add configuration system
doublevcodes/sirius pull request #6
Opened 2022-02-03 07:21 UTC by Shivansh-007

2022-02-05 13:11 UTC, doublevcodes requested changes
I seem to be hitting the following error when running `sirius dev`

```py
Traceback (most recent call last):
  File "/Users/doublevcodes/Library/Caches/pypoetry/virtualenvs/sirius-api-Oy7-IhWP-py3.10/bin/sirius", line 5, in <module>
    main()
  File "/Users/doublevcodes/Library/Caches/pypoetry/virtualenvs/sirius-api-Oy7-IhWP-py3.10/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/doublevcodes/Library/Caches/pypoetry/virtualenvs/sirius-api-Oy7-IhWP-py3.10/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/doublevcodes/Library/Caches/pypoetry/virtualenvs/sirius-api-Oy7-IhWP-py3.10/lib/python3.10/site-packages/click/core.py", line 1656, in invoke
    super().invoke(ctx)
  File "/Users/doublevcodes/Library/Caches/pypoetry/virtualenvs/sirius-api-Oy7-IhWP-py3.10/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/doublevcodes/Library/Caches/pypoetry/virtualenvs/sirius-api-Oy7-IhWP-py3.10/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/doublevcodes/Library/Caches/pypoetry/virtualenvs/sirius-api-Oy7-IhWP-py3.10/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: main() missing 1 required positional argument: 'verbose'
```

2022-02-06 12:01 UTC, doublevcodes approved these changes
Everything seems to work now!

2022-02-06 14:01 UTC, Shivansh-007 commented
Don't merge wait.

2022-02-06 14:09 UTC, Shivansh-007 commented
You can now 🎉

2022-02-06 17:01 UTC, doublevcodes requested changes
Minor bug

2022-02-06 17:01 UTC, doublevcodes commented on sirius/cli/__init__.py
> +@click.option("-p", "--port", help="Port to run the server on")
```suggestion
@click.option("-p", "--port", help="Port to run the server on", type=int)
```
This seems to fix it for me, otherwise it Uvicorn errors

2022-02-07 05:12 UTC, doublevcodes approved these changes

2022-02-07 05:12 UTC, merged

2022-02-07 05:13 UTC, doublevcodes commented
Thank you for your contribution!